ALTER TABLE user_settings 
ADD COLUMN barkDailyEnabled BOOLEAN DEFAULT TRUE,
ADD COLUMN barkWeeklyEnabled BOOLEAN DEFAULT TRUE,
ADD COLUMN barkDailyTime VARCHAR(5) DEFAULT '19:00',
ADD COLUMN barkWeeklyTime VARCHAR(5) DEFAULT '08:00';
