-- Fix balance columns to support large values (CENT accounts)
-- Change from INT to BIGINT to support values up to 9,223,372,036,854,775,807

ALTER TABLE trading_accounts 
  MODIFY COLUMN balance BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN equity BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN marginFree BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN marginUsed BIGINT NOT NULL DEFAULT 0;

ALTER TABLE trades
  MODIFY COLUMN profit BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN commission BIGINT NOT NULL DEFAULT 0,
  MODIFY COLUMN swap BIGINT NOT NULL DEFAULT 0;

ALTER TABLE balance_history
  MODIFY COLUMN balance BIGINT NOT NULL,
  MODIFY COLUMN equity BIGINT NOT NULL;
