services:
  # Web Service (API + Frontend)
  - type: web
    name: sentra-api
    runtime: node
    region: oregon
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: NODE_ENV=production node dist/index.js
    envVars:
      - key: NODE_VERSION
        value: 22.13.0
      - key: DATABASE_URL
        fromDatabase:
          name: sentra-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000

databases:
  # PostgreSQL Database
  - name: sentra-db
    databaseName: sentra_partners
    user: sentra_user
    region: oregon
    plan: free

